### ISSUE TITLE
User Validations / Login

### ISSUE THREAD

**Issue by mr-eaze** [mr-eaze/astro_app#1]
@bigtone1284 @WilliamfShaw 

Hey guys,

Simply put, I'm really not sure of how to tackle User Val / Login, and would love to get some help, pointing me in the right direction, etc.

Any help would be greatly appreciated.

Thanks!

**Comment by bigtone1284** [comment]
@mr-eaze Please take a look at w07d04 Instructor File from our class repo.  See how we implemented authentication here.

Also, look at w07d05 to see how we implementing authorization.  Give those a look and think how you can implement that in your own pj.

**Comment by mr-eaze** [comment]
ok thanks
