### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by mr-eaze** [mr-eaze/astro_app#2]
@WilliamfShaw @bigtone1284 

Having trouble getting current_user's session info.

Also, need some guidance regarding what to what to do next... and how to proceed with my app in general...

https://www.youtube.com/watch?v=1eSMxRya2S8&ab_channel=ericho33

**Comment by WilliamfShaw** [comment]
@mr-eaze Please be a bit more detailed. Follow this template and resubmit your issue. I will help us better understand what issues you are facing before coming to you. 

https://github.com/ga-students/WDI_McClane/blob/master/project_02/asking_for_help.md

**Comment by bigtone1284** [comment]
@mr-eaze any updates on this?  Also, could you give us an idea as to where you want to access the current user's info?

**Comment by mr-eaze** [comment]
@bigtone1284 

I think I figured out the session info?

Was (and still kinda am) a just a bit lost in my app structure, especially with regard to routing... but will be talking to Dan about it soon.

Ps. sorry for the vague Issue Requests... in general I'm mostly battling structural confusion, more than specific issues, and not sure how to explain it.

Will let you know if I need any more help tomorrow.

**Comment by bigtone1284** [comment]
@harimohanraj89
