### ISSUE TITLE
psql not working

### ISSUE THREAD

**Issue by mr-eaze** [mr-eaze/astro_app#3]
![screenshot 2015-04-22 13 52 22](https://cloud.githubusercontent.com/assets/5388357/7281337/026dbbae-e8f7-11e4-8272-3cb6179119c6.png)
@bigtone1284 @WilliamfShaw @harimohanraj89 @DrRobotmck 

Hey guys getting this response when I try to connect to my database via iTerm:

psql: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Really not sure what else to say...

psql (PostgreSQL) 9.4.1 is on my machine, but does not seem to be willing to let me connect.

**Comment by WilliamfShaw** [comment]
One of us will be up shortly. But cmmmmannnn man, fill out the problem submission like we have asked you to do multiple times thus far.

**Comment by WilliamfShaw** [comment]
@mr-eaze

**Comment by WilliamfShaw** [comment]
@bigtone1284 @harimohanraj89 @DrRobotmck taken
